### ISSUE TITLE
Clearer error when number of candidates <= number of winners?

### ISSUE THREAD

**Issue by tom-votes** [pbstark/CORLA18#85]
If I change the ```candidates = ``` line in https://github.com/pbstark/CORLA18/blob/master/code/suite_toolkit.ipynb to have a number of candidates less than or equal to ```num_winners``` (by default 2):

  - ```check_valid_vote_counts``` doesn't complain, but then
  - I get a somewhat-cryptic error when calling ```check_overvote_rates```:

```
ValueError: max() arg is an empty sequence
```

Dropping into ipython, I see that

```
In [1]: margins_a.values()
Out[1]: odict_values([])

In [2]: margins_a
Out[2]: OrderedDict()
```

Maybe not high-priority as those races won't need rigorous audits :smile: but confused me for a bit while doing some randomized testing, and I could imagine a misconfigured ```num_winners``` triggering this also.

**Comment by kellieotto** [comment]
Thanks! I added this as a check to `check_valid_vote_counts` so hopefully the user won't run into this problem with computing margins.
